/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "InterfaceServidorModulosServidorDisplay.h"
#include <stdbool.h>
#include <time.h>
void mostrarHoraUltimaActualizacion();
void *
enviarnotificacion_1_svc(notificacion *argp, struct svc_req *rqstp)
{
	static char *result;
	printf("\n  Modulos disponibles");
	printf("\n Turno modulo cliente");
	for (int i = 0; i < 3; i++)
	{
		if ((*argp).modulos[i].ocupado == true)
		{
			printf("\n %d	%d	%s ", (*argp).modulos[i].turno, (*argp).modulos[i].noModulo, (*argp).modulos[i].identificacionUsuario);
		}
	}

	if ((*argp).cantidadUsuariosFilaVirtual > 0)
	{
		printf("\n Cantidad de usuarios en la fila virtual: %d", (*argp).cantidadUsuariosFilaVirtual);
	}
	mostrarHoraUltimaActualizacion();
	printf("\n");

	return (void *)&result;
}
void mostrarHoraUltimaActualizacion()
{
	time_t tiempo_actual;
	struct tm *info_tiempo;

	// Obtener el tiempo actual
	time(&tiempo_actual);

	// Convertir el tiempo en una estrutura local
	info_tiempo = localtime(&tiempo_actual);

	printf("\n Ultima actualizacion: %02d:%02d\n",
		   info_tiempo->tm_hour, // Hora 0-23
		   info_tiempo->tm_min); // Minutos 0-59
}
