/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "InterfaceAdminModulosServidorModulos.h"
#include "InterfaceClienteServidorModulos.h"
#include <stdio.h>

moduloAdministrador vectorModuloAdministrador[3];
modulo vectorModulos[3];
int usuariosFilaVirtual = 0;

int *seleccionarnumeromodulo_1_svc(int *argp, struct svc_req *rqstp)
{
	static int result;

	if (vectorModuloAdministrador[*argp].estado == 0) // Verifica si el modulos está libre
	{							  
		vectorModuloAdministrador[*argp].estado = 1; // Asigna el módulo
		result = 0;				  // Éxito
		printf("Módulo %d asignado correctamente. \n", *argp);
	}
	else
	{
		result = 1;
		printf("Módulo %d ya está ocupado. \n", *argp);
	}

	return &result;
}

int *liberarmodulo_1_svc(int *argp, struct svc_req *rqstp)
{
	static int result;

	if (vectorModuloAdministrador[*argp].estado == 1) { //Verifica si el modulos está libre
		vectorModuloAdministrador[*argp].estado = 0; //Libera el módulo
		printf("Módulo %d liberado correctamente. \n", *argp);
		if(usuariosFilaVirtual > 0){
			vectorModuloAdministrador[*argp].estado = 1; //Asigna el módulo
			strcpy(vectorModulos[*argp].identificacionUsuario, filaVirtual[0].identificacionUsuario);
			printf("Módulo %d asignado a usuario %s. \n", *argp, filaVirtual[0].identificacionUsuario);
			//Mueve los usuarios en la fila
			for(int i = 0; i < usuariosFilaVirtual; i++){
				strcpy(filaVirtual[i].identificacionUsuario, filaVirtual[i+1].identificacionUsuario);
			}
			usuariosFilaVirtual--;
		}
		result = 0; //Éxito
	} else {
		result = 1;
		printf("Módulo %d ya está libre. \n", *argp);
	}

	return &result;
}
