/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "InterfaceAdminModulosServidorModulos.h"
#include <stdio.h>

moduloAdministrador vectorModuloAdministrador[3];

int *seleccionarnumeromodulo_1_svc(int *argp, struct svc_req *rqstp)
{
	static int result;

	if (vectorModuloAdministrador[*argp].estado == 0) // Verifica si el modulos está libre
	{							  
		vectorModuloAdministrador[*argp].estado = 1; // Asigna el módulo
		result = 0;				  // Éxito
		printf("Módulo %d asignado correctamente. \n", *argp);
	}
	else
	{
		result = 1;
		printf("Módulo %d ya está ocupado. \n", *argp);
	}

	return &result;
}

int *liberarmodulo_1_svc(int *argp, struct svc_req *rqstp)
{
	static int result;

	if (vectorModuloAdministrador[*argp].estado == 1) { //Verifica si el modulos está libre
		vectorModuloAdministrador[*argp].estado = 0; //Asigna el módulo
		result = 0; //Éxito
		printf("Módulo %d liberado correctamente. \n", *argp);
	} else {
		result = 1;
		printf("Módulo %d ya está libre. \n", *argp);
	}

	return &result;
}
