/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "InterfaceClienteServidorModulos.h" 
#include "InterfaceServidorModulosServidorDisplay.h"
#include <stdbool.h>

int numeroTurno=1;
int cantidadUsuariosFila=0;
usuario filaVirtual[10];
modulo vectorModulos[3];


int consultarNumeroModuloDisponible();
void notificarModulos();
nodo_turno * generarturno_1_svc(char **argp, struct svc_req *rqstp)
{
	static nodo_turno  result;
	int posicion=consultarNumeroModuloDisponible();
	printf("\n");
	if(posicion==-1){
		printf("\n Los modulos se encuentran ocupados");
		strcpy(filaVirtual[cantidadUsuariosFila].identificacionUsuario, *argp);
		cantidadUsuariosFila++;
		printf("\n El usuario se agrego a la fila virtual");
	}
	else{
		printf("\n El modulo en la posicion %d esta libre y se asignara al usuario con identificacion %s",(posicion+1),*argp);
		vectorModulos[posicion].ocupado=true;
		vectorModulos[posicion].numeroTurno=numeroTurno;
		strcpy(vectorModulos[posicion].identificacionUsuario,*argp);
	}
	result.numeroTurno=numeroTurno;
	result.cantidadUsuariosFilaVirtual=cantidadUsuariosFila;
	strcpy(result.identificacionUsuario, *argp);
	numeroTurno++;
	notificarModulos();
	printf("\n");
	
	return &result;
}
void notificarModulos()
{
	CLIENT *datosConexionServidor;
	void  *resultadoEnvio;
	char ipServidor[20];
	strcpy(ipServidor, "localhost");

#ifndef	DEBUG
// Con clnt_create se obtiene la ubicación al servidor display
	datosConexionServidor = clnt_create (ipServidor, notificar_modulos, notificar_modulos_version, "udp");
	if (datosConexionServidor == NULL) {
		clnt_pcreateerror (ipServidor);
		exit (1);
	}
#endif	/* DEBUG */
	notificacion  objNotificacion;
	for (int i=0; i<3; i++){
		strcpy(objNotificacion.modulos[i].identificacionUsuario, vectorModulos[i].identificacionUsuario);
		objNotificacion.modulos[i].noModulo = vectorModulos[i].noModulo;
		objNotificacion.modulos[i].turno = vectorModulos[i].numeroTurno;
		objNotificacion.modulos[i].ocupado = vectorModulos[i].ocupado;
	}
	objNotificacion.cantidadUsuariosFilaVirtual = cantidadUsuariosFila;
	//Se invoca el procedimiento remoto para enviar la notificación
	resultadoEnvio = enviarnotificacion_1(&objNotificacion, datosConexionServidor);
	if (resultadoEnvio == (void *) NULL) {
		clnt_perror (datosConexionServidor, "call failed");
	}
#ifndef	DEBUG
	//Se liberan recursos del lado del cliente
#endif	 /* DEBUG */
}
int consultarNumeroModuloDisponible()
{
	int posicion=-1;
	for (int i=0; i < 3; i++)
	{
		if(vectorModulos[i].ocupado==false)
		{
			posicion=i;
			break;
		}
	}
	return posicion;
}
