/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "InterfaceAdminModulosServidorModulos.h"


void
administrar_modulos_1(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	int  seleccionarnumeromodulo_1_arg;
	bool_t  *result_2;
	int  liberarmodulo_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, administrar_modulos, administrar_modulos_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = seleccionarnumeromodulo_1(&seleccionarnumeromodulo_1_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = liberarmodulo_1(&liberarmodulo_1_arg, clnt);
	if (result_2 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	administrar_modulos_1 (host);
exit (0);
}
