/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTERFACEADMINMODULOSSERVIDORMODULOS_H_RPCGEN
#define _INTERFACEADMINMODULOSSERVIDORMODULOS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct modulo {
	int numeroModulo;
	int estado;
};
typedef struct modulo modulo;

#define administrar_modulos 0x20000003
#define administrar_modulos_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define seleccionarNumeroModulo 1
extern  int * seleccionarnumeromodulo_1(int *, CLIENT *);
extern  int * seleccionarnumeromodulo_1_svc(int *, struct svc_req *);
#define liberarModulo 2
extern  int * liberarmodulo_1(int *, CLIENT *);
extern  int * liberarmodulo_1_svc(int *, struct svc_req *);
extern int administrar_modulos_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define seleccionarNumeroModulo 1
extern  int * seleccionarnumeromodulo_1();
extern  int * seleccionarnumeromodulo_1_svc();
#define liberarModulo 2
extern  int * liberarmodulo_1();
extern  int * liberarmodulo_1_svc();
extern int administrar_modulos_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_modulo (XDR *, modulo*);

#else /* K&R C */
extern bool_t xdr_modulo ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTERFACEADMINMODULOSSERVIDORMODULOS_H_RPCGEN */
