/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "InterfaceAdminModulosServidorModulos.h"

bool_t
xdr_modulo (XDR *xdrs, modulo *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->noModulo))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->estado))
		 return FALSE;
	return TRUE;
}
